#!/bin/bash

## Package manager installation command
INSTALL_COMMAND="apt-get install -q=2 -y"

## Python dependencies to be installed
PYTHON_DEPS=(numpy Beautifulsoup4 mutagen simplejson twython emoji \
             spidev BiblioPixel pillow pyserial wiringpi pyalsaaudio)

## System packages to be installed
SYSTEM_DEPS=(python3-pip python3-dev curl faad flac gcc git lame mpg123 make \
             python3-numpy python3-setuptools unzip vorbis-tools wiringpi \
             cython3 pianobar libjpeg-dev libtiff-dev libatlas-base-dev)

## Miscellaneous checks

# Recent versions of the full Raspbian distro are installing these
# Remove them so pip can install them properly
apt-get -y remove python-simplejson
apt-get -y remove python-serial

# Some versions are now installing GL by default, disable it
# if you dont, you get "Unable to enable V3D" from the FFT code
raspi-config nonint do_gldriver G3
 
# The ffmpeg library changed starting with Debian 8
# Try to install ffmpeg first, then libav-tools
echo -ne "\e[0;31mNOTE:\e[m " >&2
echo "Installing ffmpeg..."
$INSTALL_COMMAND ffmpeg || \
    (echo -ne "\e[0;31mNOTE:\e[m " >&2 && echo "Installation failed, trying libav-tools..." && \
     $INSTALL_COMMAND libav-tools && ln -fs /usr/bin/avconv /usr/bin/ffmpeg)

if [ $? -ne 0 ]; then
    echo -ne "\e[1;31mERROR:\e[m " >&2
    echo "A problem occurred while installing ffmpeg."
    exit 1
fi
